### ISSUE TITLE
Incorrect result for AES CTR 128 Bit

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/crypto#13] opened 2020-05-14 06:25 UTC
```haxe
import haxe.io.*;
import haxe.crypto.*;

class Main {
  static function main() {
    var decrypted = Bytes.ofHex('124c4e4243484b473030303531320000000c03000000000000000000001b03064327020c850308200002095e020b160a0d00ff00e7000080000097');
    var key = Bytes.ofHex('79ddd935f38f2a99cead496b9ef75f4d');
    var iv = Bytes.ofHex('b5cb4d8dd2c2fc705e10a825000043fd');
    var encrypted = Bytes.ofHex('6ac6e4f866d87942eeb002baf7b2c9d7f600bc639f30c90baffc20d7eacb83472a20d03f60e9348a651f138ffb44e27306fd3b39b5595086b491ac');
    var aes = new Aes();
    aes.init(key, iv);
    
    
    trace('encrpyt:    ${decrypted.toHex()}');
    trace('with key:   ${key.toHex()}');
    trace('with iv:    ${iv.toHex()}');
    var enc = aes.encrypt(CTR, decrypted, NoPadding);
    trace('expected:   ${encrypted.toHex()}');
    trace('calculated: ${enc.toHex()}');
    trace('match:      ' + (enc.toHex() == encrypted.toHex()));
  }
} 
```

result:
```
encrpyt:    124c4e4243484b473030303531320000000c03000000000000000000001b03064327020c850308200002095e020b160a0d00ff00e7000080000097
with key:   79ddd935f38f2a99cead496b9ef75f4d
with iv:    b5cb4d8dd2c2fc705e10a825000043fd
expected:   6ac6e4f866d87942eeb002baf7b2c9d7f600bc639f30c90baffc20d7eacb83472a20d03f60e9348a651f138ffb44e27306fd3b39b5595086b491ac
calculated: 6ac6e4f866d87942eeb002baf7b2c9d7f600bc639f30c90baffc20d7eacb83472a20d03f60e9348a651f138ffb44e2732a3858f61514161820ae9c
match:      false
```

The expected value is obtained from [this](https://cryptii.com/pipes/aes-encryption) or [this](http://www.cryptogrium.com/aes-ctr.html) site. Note that the value generated by this lib is correct up to the 48-th byte (total is 59 bytes), so I think the issue may be related to 16-byte blocks / paddings.

**Comment by Aurel300** [comment] 2020-05-14 10:25
On the latest git version this seems to work on eval, but fails on Node.js.

**Comment by kevinresol** [comment] 2020-05-14 12:02
Yeah forgot to mention, I'm on nodejs

**Comment by flashultra** [comment] 2020-05-14 12:18
Maybe this is some bug in Haxe . I trace the bug to the current example :
```haxe 
        var key = haxe.io.Bytes.ofHex('b5cb4d8dd2c2fc705e10a825000043ff');
        key.set(15, key.get(15) + 1);
        trace(key.get(15));
```
 This will show 256 in JS target and 0 for eval . The correct value should be 0.

I also test Java and Hashlink , both return 0 .

**Comment by flashultra** [comment] 2020-05-14 12:56
Open issue here : https://github.com/HaxeFoundation/haxe/issues/9415

**Comment by kevinresol** [comment] 2020-05-14 13:00
Thanks, but it is possible to put a fix (could be behind a define) here too?

**Comment by flashultra** [comment] 2020-05-14 16:24
Your fix would works, but I think the problem is from Haxe side.  If someone want to merge it and follow progress on the Haxe side , I'm ok with that.

**Comment by flashultra** [comment] 2023-11-08 13:28
Fixed with https://github.com/HaxeFoundation/crypto/pull/14

**Closed as completed by flashultra** 2023-11-08 13:28 UTC
